// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// ShortenUrLsColumns holds the columns for the "shorten_ur_ls" table.
	ShortenUrLsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "code", Type: field.TypeUUID},
	}
	// ShortenUrLsTable holds the schema information for the "shorten_ur_ls" table.
	ShortenUrLsTable = &schema.Table{
		Name:        "shorten_ur_ls",
		Columns:     ShortenUrLsColumns,
		PrimaryKey:  []*schema.Column{ShortenUrLsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ShortenUrLsTable,
	}
)

func init() {
}
