// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/cumbreras/shortener/ent/schema"
	"github.com/cumbreras/shortener/ent/shortenurl"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	shortenurlFields := schema.ShortenURL{}.Fields()
	_ = shortenurlFields
	// shortenurlDescCode is the schema descriptor for Code field.
	shortenurlDescCode := shortenurlFields[1].Descriptor()
	// shortenurl.DefaultCode holds the default value on creation for the Code field.
	shortenurl.DefaultCode = shortenurlDescCode.Default.(func() uuid.UUID)
}
