// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/cumbreras/shortener/ent/predicate"
	"github.com/cumbreras/shortener/ent/shortenurl"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// ShortenURLDelete is the builder for deleting a ShortenURL entity.
type ShortenURLDelete struct {
	config
	hooks      []Hook
	mutation   *ShortenURLMutation
	predicates []predicate.ShortenURL
}

// Where adds a new predicate to the delete builder.
func (sud *ShortenURLDelete) Where(ps ...predicate.ShortenURL) *ShortenURLDelete {
	sud.predicates = append(sud.predicates, ps...)
	return sud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sud *ShortenURLDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sud.hooks) == 0 {
		affected, err = sud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShortenURLMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sud.mutation = mutation
			affected, err = sud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sud.hooks) - 1; i >= 0; i-- {
			mut = sud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sud *ShortenURLDelete) ExecX(ctx context.Context) int {
	n, err := sud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sud *ShortenURLDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: shortenurl.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shortenurl.FieldID,
			},
		},
	}
	if ps := sud.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sud.driver, _spec)
}

// ShortenURLDeleteOne is the builder for deleting a single ShortenURL entity.
type ShortenURLDeleteOne struct {
	sud *ShortenURLDelete
}

// Exec executes the deletion query.
func (sudo *ShortenURLDeleteOne) Exec(ctx context.Context) error {
	n, err := sudo.sud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shortenurl.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sudo *ShortenURLDeleteOne) ExecX(ctx context.Context) {
	sudo.sud.ExecX(ctx)
}
