// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/cumbreras/shortener/ent/shortenurl"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// ShortenURLCreate is the builder for creating a ShortenURL entity.
type ShortenURLCreate struct {
	config
	mutation *ShortenURLMutation
	hooks    []Hook
}

// SetURL sets the URL field.
func (suc *ShortenURLCreate) SetURL(s string) *ShortenURLCreate {
	suc.mutation.SetURL(s)
	return suc
}

// SetCode sets the Code field.
func (suc *ShortenURLCreate) SetCode(u uuid.UUID) *ShortenURLCreate {
	suc.mutation.SetCode(u)
	return suc
}

// Mutation returns the ShortenURLMutation object of the builder.
func (suc *ShortenURLCreate) Mutation() *ShortenURLMutation {
	return suc.mutation
}

// Save creates the ShortenURL in the database.
func (suc *ShortenURLCreate) Save(ctx context.Context) (*ShortenURL, error) {
	var (
		err  error
		node *ShortenURL
	)
	suc.defaults()
	if len(suc.hooks) == 0 {
		if err = suc.check(); err != nil {
			return nil, err
		}
		node, err = suc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShortenURLMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suc.check(); err != nil {
				return nil, err
			}
			suc.mutation = mutation
			node, err = suc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suc.hooks) - 1; i >= 0; i-- {
			mut = suc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (suc *ShortenURLCreate) SaveX(ctx context.Context) *ShortenURL {
	v, err := suc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (suc *ShortenURLCreate) defaults() {
	if _, ok := suc.mutation.Code(); !ok {
		v := shortenurl.DefaultCode()
		suc.mutation.SetCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suc *ShortenURLCreate) check() error {
	if _, ok := suc.mutation.URL(); !ok {
		return &ValidationError{Name: "URL", err: errors.New("ent: missing required field \"URL\"")}
	}
	if _, ok := suc.mutation.Code(); !ok {
		return &ValidationError{Name: "Code", err: errors.New("ent: missing required field \"Code\"")}
	}
	return nil
}

func (suc *ShortenURLCreate) sqlSave(ctx context.Context) (*ShortenURL, error) {
	_node, _spec := suc.createSpec()
	if err := sqlgraph.CreateNode(ctx, suc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (suc *ShortenURLCreate) createSpec() (*ShortenURL, *sqlgraph.CreateSpec) {
	var (
		_node = &ShortenURL{config: suc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: shortenurl.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shortenurl.FieldID,
			},
		}
	)
	if value, ok := suc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shortenurl.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := suc.mutation.Code(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: shortenurl.FieldCode,
		})
		_node.Code = value
	}
	return _node, _spec
}

// ShortenURLCreateBulk is the builder for creating a bulk of ShortenURL entities.
type ShortenURLCreateBulk struct {
	config
	builders []*ShortenURLCreate
}

// Save creates the ShortenURL entities in the database.
func (sucb *ShortenURLCreateBulk) Save(ctx context.Context) ([]*ShortenURL, error) {
	specs := make([]*sqlgraph.CreateSpec, len(sucb.builders))
	nodes := make([]*ShortenURL, len(sucb.builders))
	mutators := make([]Mutator, len(sucb.builders))
	for i := range sucb.builders {
		func(i int, root context.Context) {
			builder := sucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShortenURLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sucb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sucb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (sucb *ShortenURLCreateBulk) SaveX(ctx context.Context) []*ShortenURL {
	v, err := sucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
