// Code generated by entc, DO NOT EDIT.

package shortenurl

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the shortenurl type in the database.
	Label = "shorten_url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"

	// Table holds the table name of the shortenurl in the database.
	Table = "shorten_ur_ls"
)

// Columns holds all SQL columns for shortenurl fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCode holds the default value on creation for the Code field.
	DefaultCode func() uuid.UUID
)
