// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// ShortenURL is the predicate function for shortenurl builders.
type ShortenURL func(*sql.Selector)
